apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.services.websub.ingress }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.websub.serviceName }}
                port:
                  number: {{ .Values.services.websub.servicePort }}