apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.websub.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.services.websub.serviceName }}
  ports:
    - port: {{ .Values.services.websub.servicePort }}
      targetPort: {{ .Values.hub.websub.port }}
