apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.workflow.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.services.workflow.ports.servicePort }}
    targetPort: {{ .Values.services.workflow.ports.workflowActionServerPort }}
  selector:
    app: {{ .Values.services.workflow.serviceName }}
