---
# Creates folder in nfs for reg-client to provide metadata.xml and mosip-cer file.
# These files are further used by reg-client downloader to create the client zip.
- include_vars: '{{versions_file}}'
- name: Create reg client folder in nfs.
  file:
    path: '{{reg_prop.nfs_path}}'
    state: directory 
  become: yes

- name: Copy certificate
  template:
    src: '{{reg_client.cert_path}}/{{reg_client.cert_file}}'
    dest: '{{reg_client.nfs_path}}' 
  become: yes

- name: copy logback.xml 
  template:
    src: '{{reg_client.logback_xml}}'
    dest: '{{reg_client.nfs_path}}'
  become: yes

- name: copy maven-metdata.xml
  template:
    src: '{{reg_client.xml_file}}'
    dest: '{{reg_client.nfs_path}}'
    force: yes
  become: yes

- import_tasks: ../certificate/cert-creator.yml
  become: yes