# Playbook to run CoreDNS server on console and configure /etc/resolv.conf
# on all machines to point to this DNS.
# Run these only if coredns is enabled.
- hosts: console
  gather_facts: true
  roles: 
      - {role: coredns, when: coredns.enabled == true} 

# Update resolv.conf file on all machines
- hosts: all
  gather_facts: false
  tasks:
   - name: Backup resolv file
     copy:
       src: '/etc/resolv.conf'
       dest: '/etc/resolv.conf.bak'
       force: false
     become: yes

   - name: Replace resolv file
     template:
       src: '{{install_root}}/roles/coredns/templates/resolv.conf.j2'
       dest: /etc/resolv.conf
     when: coredns.enabled == true
     become: yes

   - name: Create ifcfg-eth0 file
     file:
       path: /etc/sysconfig/network-scripts/ifcfg-eth0
       state: touch
     become: yes

- hosts: all:!console
  gather_facts: false
  tasks:
   - name: Allow only CoreDNS to be used by all the machines except console
     lineinfile:
       path: /etc/sysconfig/network-scripts/ifcfg-eth0
       line: 'DNS1={{ hostvars[groups.console[0]].ansible_host }}'
     become: yes

## Append 8.8.8.8 to console file 
- hosts: console
  gather_facts: false
  tasks:
   - name: Append public name server to console resolv.conf
     lineinfile:
       path: /etc/resolv.conf
       line: 'nameserver 8.8.8.8'
     become: yes
   
   - name: Create dhclient.conf file
     file:
       path: /etc/dhcp/dhclient.conf 
       state: touch
     become: yes

   - name: Append dhclient.conf for two nameservers
     lineinfile:
       path: /etc/dhcp/dhclient.conf
       line: 'supersede domain-name-servers {{ hostvars[groups.console[0]].ansible_host }}, 8.8.8.8;'
     become: yes

   - name: Allow both the DNS nameservers to be used
     lineinfile:
       path: /etc/sysconfig/network-scripts/ifcfg-eth0
       line: 'PEERDNS=yes'
     become: yes
