# This play is to execute a one time credential feeder job for Online verification partner

- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'credential-feeder'
    helm_chart: '{{charts_root}}/credential-feeder'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/credential-feeder/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

