# This play start the functional test and start scanning of API. Here we have split tasks and roles into seperate
# play as tasks only run after roles if they are in the same play (for some reason)
# and for us sequencing is important.
#
- hosts: console
  gather_facts: true
  tasks:
    - name: Clone git repo for fuctional test
      vars:
        repo_path: '{{functional_repo_path}}'
        repo_dest: '{{functional_repo_dest}}'
        version: '{{testrig_version}}'
        githubuser: ''
        githubpassword: ''
      include_role:
        name: github

- hosts: console
  gather_facts: true
  roles:
    - {role: functional-test-setup, tags: [functional-test-setup]}
    - {role: functional-test-run, tags: [functional-test-run]}