# Playbook to install softhsm
# Inputs:
#   hsm_prop structure
#   kube_config  
# 

# Prepare folders on remote node
- hosts: console
  gather_facts: true
  vars:
    hsm_prop: '{{hsm_prop}}'
  roles:
    - {role: softhsm-prep1}

# Convert helm template to helm values 
- hosts: console
  vars:
    kube_config: '{{kube_config}}'
    install_name: 'softhsm-{{hsm_prop.label}}'
    helm_chart: '{{hsm_prop.helm_chart}}'
    is_template: '{{hsm_prop.is_template}}'
    helm_namespace: '{{hsm_prop.helm_namespace}}'
    helm_values: '{{hsm_prop.helm_values}}'
    helm_strings: '{{hsm_prop.helm_strings}}'
  roles:
    - {role:  helm}

