---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.services.pktserver.pvc.name }}
  labels:
    app: {{ .Values.services.pktserver.pvc.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.services.pktserver.pv.name }}
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.services.pktserver.pvc.size}}
