apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.keymigrator.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.services.keymigrator.servicePort }}
      targetPort: {{ .Values.services.keymigrator.containerPort }}
  selector:
    app: {{ .Values.services.keymigrator.serviceName }}