podconfig:
  kernel:
    auth:
      replicas: 4 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
 
    masterdata:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
        limits:
          cpu: 500m
          memory: 1500Mi

    idgen:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi
 
    prid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 300m
          memory: 500Mi

    sync:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    audit :
      replicas: 4 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    key:
      replicas: 4 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 1000m
          memory: 2000Mi

    notifier:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    otp:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    rid:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

  regproc:
    camel:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
 
    notification: 
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    uploader:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi
 
    quality:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi
 
    validator:
      replicas: 4 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 1000m
          memory: 2000Mi
 
    osi:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    demo:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    bio:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
        limits:
          cpu: 1000m
          memory: 1500Mi

    bioauth:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    abishandler:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    abismid:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    manual:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi

    external:
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

    eis: 
      replicas: 1 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

    uin:
      replicas: 4 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    msg:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
        limits:
          cpu: 500m
          memory: 1500Mi

    print:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 500Mi

    trans:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    reprocess:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

  dmzregproc:  
    receiver:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    camel:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    status:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    pktserver:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

  prereg:
    application:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 4000Mi
        limits:
          cpu: 1000m
          memory: 4000Mi

    batch:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 40Mi
        limits:
          cpu: 500m
          memory: 40Mi
  
    booking:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 1
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi
 
    datasync:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    ui:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1  
      resources:
        requests:
          cpu: 200m
          memory: 300Mi
        limits:
          cpu: 500m
          memory: 300Mi

  ida:
    auth:
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 

    internal: 
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      requests:
        cpu: 200m
        memory: 1000Mi
      limits:
        cpu: 500m
        memory: 1000Mi

    kyc: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1

    otp: 
      replicas: 1
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 

  idrepo:
    identity:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    vid: 
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

    bioextractor:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

    credentialreq:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1 
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 1000m
          memory: 2000Mi

    credentialservice:
      replicas: 2 
      minReadySeconds: 10
      maxUnavailable: 0
      maxSurge: 1
      resources:
        requests:
          cpu: 200m
          memory: 2000Mi
        limits:
          cpu: 500m
          memory: 2000Mi

  pms:
    misp: 
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 300m
          memory: 500Mi
 
    pm:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 300m
          memory: 500Mi

    partner:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 300m
          memory: 500Mi
 
    policy:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 300m
          memory: 500Mi

  packetmanager:
    service:
      replicas: 3 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 4000Mi
        limits:
          cpu: 500m
          memory: 4000Mi
  
  resident:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
  
  activemq:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  admin:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  artifactory:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
  
  clamav:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  config_server:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
  
  datashare:
    service:
      replicas: 2 
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 500m
          memory: 1000Mi

  docker_service:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  keycloak:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  mockabis:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          cpu: 400m
          memory: 700Mi 

  postgres:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  print:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  reg_client_downloader:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  websub:
    service:
      replicas: 1
      maxSurge: 1
      maxUnavailable: 0
      minReadySeconds: 10

  ingress:
    nginx:
      replicas: 1 
