apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: {{ .Release.Namespace }} 
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.nodePortHttp }}
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: {{ .Values.nodePortHttps }} 
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
