apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.otp.serviceName }} 
  namespace: {{ .Values.ingress.namespace }}
spec:
  ports:
  - port: {{ .Values.services.otp.ports.servicePort }}
    targetPort: {{ .Values.services.otp.ports.containerPort }}
  selector:
    app: {{ .Values.services.otp.serviceName }} 

